using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Irony.Compiler;
using System.Globalization;

namespace JSBasic.Compiler.Nodes
{

	/// <summary>
	/// The root node of a BASIC program.
	/// </summary>
	internal class ProgramNode : GenericJsBasicNode, IJSBasicNode
	{

		public IEnumerable<LineNode> Lines
		{
			get
			{
				return ChildNodes.Cast<LineNode>();
			}
		}

		public ProgramNode(AstNodeArgs args)
			: base(args)
		{
		}

		#region IJSBasicNode Members

		public override void GenerateJavaScript(JSContext context, System.IO.TextWriter textWriter)
		{
			textWriter.WriteLine("/* Generated by the JSBasic compiler at " + DateTime.Now.ToString("HH:mm:ss dd/MMM/yy", CultureInfo.CurrentCulture) + " */");
			foreach (LineNode line in Lines)
			{
				line.GenerateJavaScript(context, textWriter);
			}
		}

		#endregion
	}
}
